Repository hibiken/asynq, pull requests merged in 2024-10, with the labels that each got.

#743 Archived tasks that are trimmed from the set are deleted
  internal/rdb/rdb.go
  internal/rdb/rdb_test.go
Labels: pr-bugfix, investigate, ready-to-merge

#585 [RFC] Adds Ping() to client/scheduler/server
  client.go
  scheduler.go
  server.go
Labels: pr-feat, pr-non-breaking, ready-for-review

#876 fix testing errors caused by possible inconsistent scores between ProcessIn and ProcessAt
  client_test.go
Labels: ready-for-review

#882 feature: revoke task
  processor.go
  processor_test.go
  server.go
Labels: pr-feat, ready-for-review

#868 Add jitter on the processor fetch backoff sleep
  processor.go
Labels: performance, pr-feat, pr-non-breaking

#927 Run golangci-lint in CI
  .github/workflows/build.yml
  Makefile
  benchmark_test.go
  client.go
  client_test.go
  heartbeat.go
  internal/base/base.go
  internal/rdb/rdb_test.go
  periodic_task_manager.go
  processor_test.go
  scheduler.go
  server_test.go
Labels: pr-ci/cd

#928 Configure dependabot to update Github Actions
  .github/dependabot.yaml
Labels: pr-ci/cd

#918 Add task enqueue command to cli
  tools/asynq/cmd/root.go
  tools/asynq/cmd/task.go
Labels: pr-feat, pr-non-breaking, ready-to-merge
